// <auto-generated/>
// Design-time stubs for editors that don't run the WPF XAML compiler (e.g., VS Code).
// These are included ONLY for DesignTimeBuild so runtime builds still use the real generated XAML partial classes.

namespace PeP.ExamApp.Controls
{
    public partial class ExamTaskbar
    {
        private void InitializeComponent() { }

        internal System.Windows.Controls.TextBlock ExamTitleText { get; } = new();
        internal System.Windows.Controls.TextBlock ClockText { get; } = new();
        internal System.Windows.Controls.TextBlock DateText { get; } = new();
        internal System.Windows.Controls.Border ViolationBorder { get; } = new();
        internal System.Windows.Controls.TextBlock ViolationCountText { get; } = new();
        internal System.Windows.Shapes.Ellipse InternetIndicator { get; } = new();
        internal System.Windows.Controls.TextBlock InternetStatusText { get; } = new();
        internal System.Windows.Controls.Primitives.Popup NetworkPopup { get; } = new();
        internal NetworkPanel NetworkPanelControl { get; } = new();
    }

    public partial class NetworkPanel
    {
        private void InitializeComponent() { }

        internal System.Windows.Controls.TextBlock ConnectionStatusText { get; } = new();
        internal System.Windows.Controls.TextBlock ConnectionIcon { get; } = new();
        internal System.Windows.Controls.TextBlock CurrentNetworkName { get; } = new();
        internal System.Windows.Controls.TextBlock CurrentNetworkType { get; } = new();
        internal System.Windows.Controls.Button DisconnectButton { get; } = new();
        internal System.Windows.Controls.Button RefreshButton { get; } = new();
        internal System.Windows.Controls.Border LoadingPanel { get; } = new();
        internal System.Windows.Controls.ListBox NetworkList { get; } = new();
        internal System.Windows.Controls.Border NoNetworksPanel { get; } = new();
        internal System.Windows.Controls.Border EthernetStatus { get; } = new();
        internal System.Windows.Controls.TextBlock EthernetStatusText { get; } = new();
    }

    public partial class WiFiPasswordDialog
    {
        private void InitializeComponent() { }

        internal System.Windows.Controls.TextBlock NetworkNameText { get; } = new();
        internal System.Windows.Controls.PasswordBox PasswordInput { get; } = new();
        internal System.Windows.Controls.TextBlock ErrorText { get; } = new();
    }
}

namespace PeP.ExamApp.Pages
{
    public partial class ConnectPage
    {
        private void InitializeComponent() { }

        internal System.Windows.Controls.TextBox ServerUrlTextBox { get; } = new();
        internal System.Windows.Controls.TextBlock ErrorText { get; } = new();
    }

    public partial class LoginPage
    {
        private void InitializeComponent() { }

        internal System.Windows.Controls.TextBox EmailTextBox { get; } = new();
        internal System.Windows.Controls.PasswordBox PasswordBox { get; } = new();
        internal System.Windows.Controls.TextBlock StatusText { get; } = new();
        internal System.Windows.Controls.TextBlock ErrorText { get; } = new();
        internal System.Windows.Controls.Button SignInButton { get; } = new();
    }

    public partial class ExamCodePage
    {
        private void InitializeComponent() { }

        internal System.Windows.Controls.TextBox CodeTextBox { get; } = new();
        internal System.Windows.Controls.Button LookupButton { get; } = new();
        internal System.Windows.Controls.Button ContinueButton { get; } = new();
        internal System.Windows.Controls.TextBlock StatusText { get; } = new();
        internal System.Windows.Controls.TextBlock ErrorText { get; } = new();

        internal System.Windows.Controls.TextBlock ExamTitleText { get; } = new();
        internal System.Windows.Controls.TextBlock CourseText { get; } = new();
        internal System.Windows.Controls.TextBlock TeacherText { get; } = new();
        internal System.Windows.Controls.TextBlock DurationText { get; } = new();
    }

    public partial class TeacherAuthPage
    {
        private void InitializeComponent() { }

        internal System.Windows.Controls.TextBlock ExamText { get; } = new();
        internal System.Windows.Controls.TextBlock TeacherText { get; } = new();
        internal System.Windows.Controls.PasswordBox TeacherPasswordBox { get; } = new();
        internal System.Windows.Controls.TextBlock StatusText { get; } = new();
        internal System.Windows.Controls.TextBlock ErrorText { get; } = new();
        internal System.Windows.Controls.Button AuthorizeButton { get; } = new();
    }

    public partial class TutorialPage
    {
        private void InitializeComponent() { }

        internal System.Windows.Controls.CheckBox AcknowledgeCheckBox { get; } = new();
        internal System.Windows.Controls.Button ContinueButton { get; } = new();
    }

    public partial class AntiCheatPage
    {
        private void InitializeComponent() { }
    }

    public partial class ExamRunnerPage
    {
        private void InitializeComponent() { }

        internal Microsoft.Web.WebView2.Wpf.WebView2 ExamWebView { get; } = new();
        internal System.Windows.FrameworkElement Overlay { get; } = new System.Windows.Controls.Border();
        internal System.Windows.Controls.TextBlock OverlayErrorText { get; } = new();
    }
}

